name: Static website infrastructure deployment
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - "main" #Focus on the main branch
  pull_request:
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest #Runner. Severless

    steps:
      - name: Checkout code/ Download code
        uses: actions/checkout@v4 #Download code into runner for further CICD operations
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY_}}
          aws-region: us-east-1
      - name: Runs Terraform init
        run: terraform init
      - name: Terraform validate
        run: terraform validate
      - name: Terraform plan
        # run: terraform plan -out=plan.out
        run: terraform plan
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        # run: terraform apply -auto-approve plan.out
        run: terraform apply
